from .criar_aluno import criar_aluno
from .criar_atletica import criar_atletica
from .listar_estatisticas import listar_estatisticas
from .criar_usuario import criar_usuario
from .feed_personalizado import feed_personalizado
from .listar_eventos_atletica import listar_eventos_atletica
from .inscrever_usuario_evento import inscrever_usuario_evento
from .listar_participacoes_comuns import listar_participacoes_comuns